// AUTO-GENERATED by scripts/sync-docs.mjs from docs/website/*.md frontmatter.
// Do not edit by hand — change a doc's nav_section / nav_order instead.
// Committed so the site builds on a fresh checkout before the sync runs.

import type { NavSection } from "./site";

export const docsNav: NavSection[] = [
  {
    title: "Getting Started",
    items: [
      { title: "Introduction", href: "/docs" },
      { title: "Installation", href: "/docs/installation" },
      { title: "Quick Start", href: "/docs/quick-start" },
      { title: "Authentication", href: "/docs/authentication" },
      { title: "Providers & Models", href: "/docs/providers" },
    ],
  },
  {
    title: "User Manual",
    items: [
      { title: "The Interface", href: "/docs/interface" },
      { title: "Keybindings", href: "/docs/keybindings" },
      { title: "Permission Profiles", href: "/docs/profiles" },
      { title: "Threads & Persistence", href: "/docs/threads" },
      { title: "Configuration", href: "/docs/configuration" },
      { title: "CLI Reference", href: "/docs/cli" },
    ],
  },
  {
    title: "Tools",
    items: [
      { title: "Tool Overview", href: "/docs/tools" },
      { title: "Sandboxing", href: "/docs/sandboxing" },
      { title: "Workspace Boundary", href: "/docs/workspace" },
    ],
  },
  {
    title: "Advanced",
    items: [
      { title: "SSH Air-gap", href: "/docs/airgap" },
      { title: "Zed / ACP", href: "/docs/acp" },
      { title: "MCP Server", href: "/docs/mcp" },
      { title: "Agent Skills", href: "/docs/skills" },
      { title: "Corporate Proxies", href: "/docs/proxies" },
      { title: "Building from Source", href: "/docs/building" },
      { title: "Architecture", href: "/docs/architecture" },
    ],
  },
  {
    title: "Help",
    items: [
      { title: "Troubleshooting", href: "/docs/troubleshooting" },
      { title: "FAQ", href: "/docs/faq" },
    ],
  },
];
