// AUTO-GENERATED by scripts/sync-docs.mjs from docs/website/*.md frontmatter.
// Do not edit by hand — change a doc's nav_section / nav_order instead.
// Committed so the site builds on a fresh checkout before the sync runs.

import type { NavSection } from "./site";

export const docsNav: NavSection[] = [
  {
    title: "Getting Started",
    items: [
      { title: "Introduction", href: "/docs" },
      { title: "agentty vs Claude Code", href: "/docs/vs-claude-code" },
      { title: "Installation", href: "/docs/installation" },
      { title: "Quick Start", href: "/docs/quick-start" },
      { title: "Authentication", href: "/docs/authentication" },
      { title: "Providers & Models", href: "/docs/providers" },
    ],
  },
  {
    title: "User Manual",
    items: [
      { title: "The Interface", href: "/docs/interface" },
      { title: "Keybindings", href: "/docs/keybindings" },
      { title: "Permission Profiles", href: "/docs/profiles" },
      { title: "Threads & Persistence", href: "/docs/threads" },
      { title: "Forking a Thread", href: "/docs/fork" },
      { title: "Configuration", href: "/docs/configuration" },
      { title: "Smart Mode", href: "/docs/smart-mode" },
      { title: "Smart Mode: Roles & Routing", href: "/docs/smart-mode-routing" },
      { title: "Smart Mode: Orchestration", href: "/docs/smart-mode-orchestration" },
      { title: "Smart Mode: Learning", href: "/docs/smart-mode-learning" },
      { title: "Smart Mode: Reference", href: "/docs/smart-mode-reference" },
      { title: "CLI Reference", href: "/docs/cli" },
    ],
  },
  {
    title: "Tools",
    items: [
      { title: "Tool Overview", href: "/docs/tools" },
      { title: "Sandboxing", href: "/docs/sandboxing" },
      { title: "Workspace Boundary", href: "/docs/workspace" },
      { title: "Retrieval (RAG)", href: "/docs/retrieval" },
      { title: "Hooks", href: "/docs/hooks" },
      { title: "Subagents", href: "/docs/subagents" },
      { title: "Slash Commands", href: "/docs/slash-commands" },
    ],
  },
  {
    title: "Advanced",
    items: [
      { title: "SSH Air-gap", href: "/docs/airgap" },
      { title: "Zed / ACP", href: "/docs/acp" },
      { title: "MCP Server", href: "/docs/mcp" },
      { title: "Plugins (MCP servers)", href: "/docs/plugins" },
      { title: "Build a Plugin", href: "/docs/build-a-plugin" },
      { title: "Plugin Trust", href: "/docs/plugin-trust" },
      { title: "Agent Skills", href: "/docs/skills" },
      { title: "Corporate Proxies", href: "/docs/proxies" },
      { title: "Building from Source", href: "/docs/building" },
      { title: "Architecture", href: "/docs/architecture" },
      { title: "Why modern C++ (not Rust)", href: "/docs/why-not-rust" },
      { title: "The Rust critique, answered", href: "/docs/rust-critique" },
    ],
  },
  {
    title: "Help",
    items: [
      { title: "Troubleshooting", href: "/docs/troubleshooting" },
      { title: "FAQ", href: "/docs/faq" },
    ],
  },
];
