// AUTO-GENERATED by scripts/fetch-release.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub Releases API on each deploy so the published-artifact
// version / size / per-platform downloads never drift. Last fetched: 2026-07-20T21:16:04.836Z.

export const latestRelease = {
  "version": "0.2.8",
  "tag": "v0.2.8",
  "name": "v0.2.8",
  "htmlUrl": "https://github.com/1ay1/agentty/releases/tag/v0.2.8",
  "publishedAt": "2026-07-16T17:25:46Z",
  "prerelease": false,
  "headlineSizeMB": "14.1 MB",
  "headlineSizeBytes": 14753024,
  "headlineUrl": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-linux-x86_64",
  "totalDownloads": 42,
  "platforms": [
    {
      "key": "linux-x86_64",
      "label": "Linux · x86_64",
      "name": "agentty-linux-x86_64",
      "sizeBytes": 14753024,
      "sizeMB": "14.1 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-linux-x86_64",
      "sha256": "84a701fb3144484636dba98a90399c5f6ab44159944f40e91e64dbcdf89878aa"
    },
    {
      "key": "linux-aarch64",
      "label": "Linux · aarch64",
      "name": "agentty-linux-aarch64",
      "sizeBytes": 12548960,
      "sizeMB": "12.0 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-linux-aarch64",
      "sha256": "24929b7cff338c8cfd349ae83510c2a56d4c9ec72458db1e7280b8e50bee425f"
    },
    {
      "key": "macos-arm64",
      "label": "macOS · Apple Silicon",
      "name": "agentty-macos-arm64",
      "sizeBytes": 23856088,
      "sizeMB": "22.8 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-macos-arm64",
      "sha256": "d92e448e00c7605418124c02670eff6cbfcb30ad975e553a71d98f346b9d4cd7"
    },
    {
      "key": "macos-x86_64",
      "label": "macOS · Intel",
      "name": "agentty-macos-x86_64",
      "sizeBytes": 28494440,
      "sizeMB": "27.2 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-macos-x86_64",
      "sha256": "9d6a3fd1df6ecb39aae492df5fd33f148e8757f2c23e13fc4496b69b059c5317"
    },
    {
      "key": "windows-x86_64",
      "label": "Windows · x86_64",
      "name": "agentty-windows-x86_64.exe",
      "sizeBytes": 14422528,
      "sizeMB": "13.8 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-windows-x86_64.exe",
      "sha256": "be64e7aa7987c1cbe1d9287f150b024248aaa97e2e5250d0ab84f7ce2b962f06"
    }
  ],
  "fetchedAt": "2026-07-20T21:16:04.836Z"
} as const;

export type LatestRelease = typeof latestRelease;
