// AUTO-GENERATED by scripts/fetch-release.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub Releases API on each deploy so the published-artifact
// version / size / per-platform downloads never drift. Last fetched: 2026-07-17T01:13:08.935Z.

export const latestRelease = {
  "version": "0.2.8",
  "tag": "v0.2.8",
  "name": "v0.2.8",
  "htmlUrl": "https://github.com/1ay1/agentty/releases/tag/v0.2.8",
  "publishedAt": "2026-07-16T17:25:46Z",
  "prerelease": false,
  "headlineSizeMB": "13.6 MB",
  "headlineSizeBytes": 14264512,
  "headlineUrl": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-linux-x86_64",
  "totalDownloads": 106,
  "platforms": [
    {
      "key": "linux-x86_64",
      "label": "Linux · x86_64",
      "name": "agentty-linux-x86_64",
      "sizeBytes": 14264512,
      "sizeMB": "13.6 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-linux-x86_64",
      "sha256": "5a41dba98d81c53ea885009f955b5a5f1b87be20697a9e159772d71bea2ab09d"
    },
    {
      "key": "linux-aarch64",
      "label": "Linux · aarch64",
      "name": "agentty-linux-aarch64",
      "sizeBytes": 12154712,
      "sizeMB": "11.6 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-linux-aarch64",
      "sha256": "f5ff9b99c75ba6405e80147d4a375627f1f267451ba822a8748479ca62f48bf0"
    },
    {
      "key": "macos-arm64",
      "label": "macOS · Apple Silicon",
      "name": "agentty-macos-arm64",
      "sizeBytes": 22506776,
      "sizeMB": "21.5 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-macos-arm64",
      "sha256": "eb421c4e49e83df968bac4037ac84bec8827dab8e0543154a14dbe605ceab88e"
    },
    {
      "key": "macos-x86_64",
      "label": "macOS · Intel",
      "name": "agentty-macos-x86_64",
      "sizeBytes": 27019208,
      "sizeMB": "25.8 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-macos-x86_64",
      "sha256": "2fc0574e10fb43e5df61b5b643377da52d3188da2f4814b493fc4c5f6299e04d"
    },
    {
      "key": "windows-x86_64",
      "label": "Windows · x86_64",
      "name": "agentty-windows-x86_64.exe",
      "sizeBytes": 13847040,
      "sizeMB": "13.2 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.2.8/agentty-windows-x86_64.exe",
      "sha256": "8b108f09a62220136383835b52f1506f003e6da246a9b1335846ab3e11733fff"
    }
  ],
  "fetchedAt": "2026-07-17T01:13:08.935Z"
} as const;

export type LatestRelease = typeof latestRelease;
