// AUTO-GENERATED by scripts/fetch-release.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub Releases API on each deploy so the published-artifact
// version / size / per-platform downloads never drift. Last fetched: 2026-06-02T10:05:30.520Z.

export const latestRelease = {
  "version": "0.1.0",
  "tag": "v0.1.0",
  "name": "v0.1.0",
  "htmlUrl": "https://github.com/1ay1/agentty/releases/tag/v0.1.0",
  "publishedAt": "2026-06-01T14:36:44Z",
  "prerelease": false,
  "headlineSizeMB": "9.4 MB",
  "headlineSizeBytes": 9862104,
  "headlineUrl": "https://github.com/1ay1/agentty/releases/download/v0.1.0/agentty-linux-x86_64",
  "totalDownloads": 47,
  "platforms": [
    {
      "key": "linux-x86_64",
      "label": "Linux · x86_64",
      "name": "agentty-linux-x86_64",
      "sizeBytes": 9862104,
      "sizeMB": "9.4 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.1.0/agentty-linux-x86_64",
      "sha256": "7a2f6160b60c6f5aad390b7652158d519706dd0f4874c72acbe245a8f2201730"
    },
    {
      "key": "linux-aarch64",
      "label": "Linux · aarch64",
      "name": "agentty-linux-aarch64",
      "sizeBytes": 8546960,
      "sizeMB": "8.2 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.1.0/agentty-linux-aarch64",
      "sha256": "62f7a2b804851b56ab5aa7d6ee29fb59446f5eaae0b9948f9cd7dce832076f37"
    },
    {
      "key": "macos-arm64",
      "label": "macOS · Apple Silicon",
      "name": "agentty-macos-arm64",
      "sizeBytes": 23154488,
      "sizeMB": "22.1 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.1.0/agentty-macos-arm64",
      "sha256": "c1d070509ebd0978b4809a5bed18e772463862a3750fb9abfcff5ec223d1d8ac"
    },
    {
      "key": "macos-x86_64",
      "label": "macOS · Intel",
      "name": "agentty-macos-x86_64",
      "sizeBytes": 26075720,
      "sizeMB": "24.9 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.1.0/agentty-macos-x86_64",
      "sha256": "23d6c5ac7355a5bef77973c49218009fc53af28d3c0cff9a613b42b3a23571cb"
    },
    {
      "key": "windows-x86_64",
      "label": "Windows · x86_64",
      "name": "agentty-windows-x86_64.exe",
      "sizeBytes": 8978432,
      "sizeMB": "8.6 MB",
      "url": "https://github.com/1ay1/agentty/releases/download/v0.1.0/agentty-windows-x86_64.exe",
      "sha256": "4f6fe2b3fedef8a6e920439a111a79c99f24e0b32f2c6a9982941c2450451758"
    }
  ],
  "fetchedAt": "2026-06-02T10:05:30.520Z"
} as const;

export type LatestRelease = typeof latestRelease;
