// AUTO-GENERATED by scripts/fetch-repo.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub repo API on each deploy so the site's star / fork
// counts never drift from the real repo. Last fetched: 2026-08-19T19:48:36.128Z.

export const repoStats = {
  "stars": 605,
  "forks": 17,
  "openIssues": 0,
  "watchers": 2,
  "description": "AI pair programming in your terminal — one static binary, sub-ms startup, any model",
  "htmlUrl": "https://github.com/1ay1/agentty",
  "pushedAt": "2026-08-19T19:46:57Z",
  "fetchedAt": "2026-08-19T19:48:36.128Z"
} as const;

export type RepoStats = typeof repoStats;
