// AUTO-GENERATED by scripts/fetch-repo.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub repo API on each deploy so the site's star / fork
// counts never drift from the real repo. Last fetched: 2026-07-20T20:34:57.173Z.

export const repoStats = {
  "stars": 83,
  "forks": 6,
  "openIssues": 0,
  "watchers": 0,
  "description": "AI pair programming in your terminal — one static binary, sub-ms startup, any model",
  "htmlUrl": "https://github.com/1ay1/agentty",
  "pushedAt": "2026-07-20T18:38:02Z",
  "fetchedAt": "2026-07-20T20:34:57.173Z"
} as const;

export type RepoStats = typeof repoStats;
