// AUTO-GENERATED by scripts/fetch-repo.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub repo API on each deploy so the site's star / fork
// counts never drift from the real repo. Last fetched: 2026-10-02T01:22:17.052Z.

export const repoStats = {
  "stars": 614,
  "forks": 24,
  "openIssues": 1,
  "watchers": 2,
  "description": "AI pair programming in your terminal — one static binary, sub-ms startup, any model",
  "htmlUrl": "https://github.com/1ay1/agentty",
  "pushedAt": "2026-10-01T20:54:19Z",
  "fetchedAt": "2026-10-02T01:22:17.052Z"
} as const;

export type RepoStats = typeof repoStats;
