// AUTO-GENERATED by scripts/measure-stats.mjs — DO NOT EDIT BY HAND.
// Regenerated on every deploy from the real agentty binary, so the site can
// never drift from what actually ships. Last measured: 2026-08-19T19:56:51.551Z.

export const measuredStats = {
  "binarySizeBytes": 17484928,
  "binarySizeMB": "16.7 MB",
  "version": "0.3.0",
  "staticLinked": true,
  "coldStartMs": 2.98,
  "coldStartLabel": "~3 ms",
  "versionMs": 3.1,
  "helpMs": 2.98,
  "measuredAt": "2026-08-19T19:56:51.551Z",
  "source": "/home/ayush/.local/bin/agentty"
} as const;

export type MeasuredStats = typeof measuredStats;
