// AUTO-GENERATED by scripts/measure-stats.mjs — DO NOT EDIT BY HAND.
// Regenerated on every deploy from the real agentty binary, so the site can
// never drift from what actually ships. Last measured: 2026-07-17T01:08:15.983Z.

export const measuredStats = {
  "binarySizeBytes": 14264512,
  "binarySizeMB": "13.6 MB",
  "version": "0.2.8",
  "staticLinked": true,
  "coldStartMs": 2.4,
  "coldStartLabel": "~2 ms",
  "versionMs": 2.56,
  "helpMs": 2.4,
  "measuredAt": "2026-07-17T01:08:15.983Z",
  "source": "/home/ayush/.local/bin/agentty"
} as const;

export type MeasuredStats = typeof measuredStats;
