#!/usr/bin/env node
// Fetch the latest GitHub release for agentty and emit lib/release.generated.ts
// so the site's "latest version / published artifact size / per-platform
// downloads" stay in sync with what's actually published — no hand-editing.
//
// Run by deploy.sh before the build. NEVER fails the deploy: on any network
// error, rate-limit, or missing data it leaves the committed file untouched
// and exits 0.
//
//   node scripts/fetch-release.mjs            # public, unauthenticated (60/hr)
//   GITHUB_TOKEN=ghp_… node scripts/...       # authenticated (5000/hr)

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "lib", "release.generated.ts");
const REPO = process.env.AGENTTY_REPO || "1ay1/agentty";
const API = `https://api.github.com/repos/${REPO}/releases/latest`;

function bail(msg) {
  console.warn(`[fetch-release] ${msg} — keeping committed release data.`);
  process.exit(0); // never break the deploy
}

const headers = {
  "User-Agent": "agentty-site-build",
  Accept: "application/vnd.github+json",
};
if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;

const PLATFORMS = [
  { key: "linux-x86_64", label: "Linux · x86_64", re: /linux-(x86_64|amd64)$/i },
  { key: "linux-aarch64", label: "Linux · aarch64", re: /linux-(aarch64|arm64)$/i },
  { key: "macos-arm64", label: "macOS · Apple Silicon", re: /(macos|darwin)-(arm64|aarch64)$/i },
  { key: "macos-x86_64", label: "macOS · Intel", re: /(macos|darwin)-(x86_64|amd64)$/i },
  { key: "windows-x86_64", label: "Windows · x86_64", re: /(windows|win)-(x86_64|amd64).*(\.exe)?$/i },
];

const mb = (bytes) => `${(bytes / 1048576).toFixed(1)} MB`;

// True only for the raw standalone binaries (agentty-<os>-<arch>) that the
// curl|sh installer pulls — not the .deb/.rpm/.pkg/.tar.gz wrappers. A release
// that has uploaded ONLY a source tarball (binary build jobs still running, or
// failed) has none of these, and we must not let it blank the site.
const hasBinaries = (rel) => {
  const assets = Array.isArray(rel?.assets) ? rel.assets : [];
  return PLATFORMS.some((p) => assets.some((a) => p.re.test(a.name)));
};

async function fetchJson(url) {
  const ctrl = new AbortController();
  const to = setTimeout(() => ctrl.abort(), 10000);
  try {
    const res = await fetch(url, { headers, signal: ctrl.signal });
    if (!res.ok) return { error: `GitHub API returned ${res.status}` };
    return { data: await res.json() };
  } catch (e) {
    return { error: `fetch failed: ${e?.message ?? e}` };
  } finally {
    clearTimeout(to);
  }
}

// Prefer the GitHub-designated "latest" release. If it hasn't uploaded its
// per-platform binaries yet (streaming release: source tarball lands first),
// walk the recent releases and use the newest one that actually has binaries,
// so the install page never loses its download table mid-publish.
let rel;
const latest = await fetchJson(API);
if (latest.error) bail(latest.error);
if (hasBinaries(latest.data)) {
  rel = latest.data;
} else {
  console.warn(
    `[fetch-release] latest (${latest.data?.tag_name ?? "?"}) has no standalone binaries yet — ` +
      `looking back for the newest release that does.`,
  );
  const list = await fetchJson(
    `https://api.github.com/repos/${REPO}/releases?per_page=20`,
  );
  const releases = Array.isArray(list.data) ? list.data : [];
  rel =
    releases.find((r) => !r.draft && hasBinaries(r)) || latest.data;
}

const assets = Array.isArray(rel.assets) ? rel.assets : [];

const platforms = [];
for (const p of PLATFORMS) {
  const a = assets.find((x) => p.re.test(x.name));
  if (a) {
    platforms.push({
      key: p.key,
      label: p.label,
      name: a.name,
      sizeBytes: a.size,
      sizeMB: mb(a.size),
      url: a.browser_download_url,
      sha256: (a.digest || "").replace(/^sha256:/, "") || null,
    });
  }
}

// Headline binary = the Linux x86_64 standalone (what curl|sh installs most).
const headline =
  platforms.find((p) => p.key === "linux-x86_64") || platforms[0] || null;

const totalDownloads = assets.reduce((n, a) => n + (a.download_count || 0), 0);

const data = {
  version: (rel.tag_name || rel.name || "").replace(/^v/, ""),
  tag: rel.tag_name || "",
  name: rel.name || rel.tag_name || "",
  htmlUrl: rel.html_url || `https://github.com/${REPO}/releases/latest`,
  publishedAt: rel.published_at || "",
  prerelease: !!rel.prerelease,
  headlineSizeMB: headline ? headline.sizeMB : null,
  headlineSizeBytes: headline ? headline.sizeBytes : null,
  headlineUrl: headline ? headline.url : null,
  totalDownloads,
  platforms,
  fetchedAt: new Date().toISOString(),
};

const banner = `// AUTO-GENERATED by scripts/fetch-release.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub Releases API on each deploy so the published-artifact
// version / size / per-platform downloads never drift. Last fetched: ${data.fetchedAt}.
`;
const body = `export const latestRelease = ${JSON.stringify(data, null, 2)} as const;

export type LatestRelease = typeof latestRelease;
`;

writeFileSync(OUT, banner + "\n" + body);

console.log(
  `[fetch-release] ${REPO} @ ${data.tag || "(no tag)"}\n` +
    `  version    : ${data.version || "(unknown)"}\n` +
    `  published  : ${data.publishedAt}\n` +
    `  headline   : ${data.headlineSizeMB ?? "—"} (${headline?.name ?? "no standalone binary"})\n` +
    `  platforms  : ${platforms.map((p) => p.key).join(", ") || "none"}\n` +
    `  downloads  : ${totalDownloads}\n` +
    `  → wrote ${OUT}`,
);
