#!/usr/bin/env node
// Fetch the latest GitHub release for agentty and emit lib/release.generated.ts
// so the site's "latest version / published artifact size / per-platform
// downloads" stay in sync with what's actually published — no hand-editing.
//
// Run by deploy.sh before the build. NEVER fails the deploy: on any network
// error, rate-limit, or missing data it leaves the committed file untouched
// and exits 0.
//
//   node scripts/fetch-release.mjs            # public, unauthenticated (60/hr)
//   GITHUB_TOKEN=ghp_… node scripts/...       # authenticated (5000/hr)

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "lib", "release.generated.ts");
const REPO = process.env.AGENTTY_REPO || "1ay1/agentty";
const API = `https://api.github.com/repos/${REPO}/releases/latest`;

function bail(msg) {
  console.warn(`[fetch-release] ${msg} — keeping committed release data.`);
  process.exit(0); // never break the deploy
}

const headers = {
  "User-Agent": "agentty-site-build",
  Accept: "application/vnd.github+json",
};
if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;

let rel;
try {
  const ctrl = new AbortController();
  const to = setTimeout(() => ctrl.abort(), 10000);
  const res = await fetch(API, { headers, signal: ctrl.signal });
  clearTimeout(to);
  if (!res.ok) bail(`GitHub API returned ${res.status}`);
  rel = await res.json();
} catch (e) {
  bail(`fetch failed: ${e?.message ?? e}`);
}

const assets = Array.isArray(rel.assets) ? rel.assets : [];
if (assets.length === 0) bail("release has no assets");

const mb = (bytes) => `${(bytes / 1048576).toFixed(1)} MB`;

// Classify each raw (non-package) executable asset by platform/arch. We match
// the standalone binaries (agentty-<os>-<arch>), which are the curl-installed
// artifacts — not the .rpm/.deb/.pkg/.tar.gz wrappers.
const PLATFORMS = [
  { key: "linux-x86_64", label: "Linux · x86_64", re: /linux-(x86_64|amd64)$/i },
  { key: "linux-aarch64", label: "Linux · aarch64", re: /linux-(aarch64|arm64)$/i },
  { key: "macos-arm64", label: "macOS · Apple Silicon", re: /(macos|darwin)-(arm64|aarch64)$/i },
  { key: "macos-x86_64", label: "macOS · Intel", re: /(macos|darwin)-(x86_64|amd64)$/i },
  { key: "windows-x86_64", label: "Windows · x86_64", re: /(windows|win)-(x86_64|amd64).*(\.exe)?$/i },
];

const platforms = [];
for (const p of PLATFORMS) {
  const a = assets.find((x) => p.re.test(x.name));
  if (a) {
    platforms.push({
      key: p.key,
      label: p.label,
      name: a.name,
      sizeBytes: a.size,
      sizeMB: mb(a.size),
      url: a.browser_download_url,
      sha256: (a.digest || "").replace(/^sha256:/, "") || null,
    });
  }
}

// Headline binary = the Linux x86_64 standalone (what curl|sh installs most).
const headline =
  platforms.find((p) => p.key === "linux-x86_64") || platforms[0] || null;

const totalDownloads = assets.reduce((n, a) => n + (a.download_count || 0), 0);

const data = {
  version: (rel.tag_name || rel.name || "").replace(/^v/, ""),
  tag: rel.tag_name || "",
  name: rel.name || rel.tag_name || "",
  htmlUrl: rel.html_url || `https://github.com/${REPO}/releases/latest`,
  publishedAt: rel.published_at || "",
  prerelease: !!rel.prerelease,
  headlineSizeMB: headline ? headline.sizeMB : null,
  headlineSizeBytes: headline ? headline.sizeBytes : null,
  headlineUrl: headline ? headline.url : null,
  totalDownloads,
  platforms,
  fetchedAt: new Date().toISOString(),
};

const banner = `// AUTO-GENERATED by scripts/fetch-release.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub Releases API on each deploy so the published-artifact
// version / size / per-platform downloads never drift. Last fetched: ${data.fetchedAt}.
`;
const body = `export const latestRelease = ${JSON.stringify(data, null, 2)} as const;

export type LatestRelease = typeof latestRelease;
`;

writeFileSync(OUT, banner + "\n" + body);

console.log(
  `[fetch-release] ${REPO} @ ${data.tag || "(no tag)"}\n` +
    `  version    : ${data.version || "(unknown)"}\n` +
    `  published  : ${data.publishedAt}\n` +
    `  headline   : ${data.headlineSizeMB ?? "—"} (${headline?.name ?? "no standalone binary"})\n` +
    `  platforms  : ${platforms.map((p) => p.key).join(", ") || "none"}\n` +
    `  downloads  : ${totalDownloads}\n` +
    `  → wrote ${OUT}`,
);
