#!/usr/bin/env node
// Fetch the agentty GitHub repo's social stats (stars / forks / open issues)
// and emit lib/repo.generated.ts so the site can show a live "★ N on GitHub"
// figure that never drifts from the real repo — no hand-editing.
//
// Run by deploy.sh before the build. NEVER fails the deploy: on any network
// error, rate-limit, or missing data it leaves the committed file untouched
// and exits 0.
//
//   node scripts/fetch-repo.mjs               # public, unauthenticated (60/hr)
//   GITHUB_TOKEN=ghp_… node scripts/...       # authenticated (5000/hr)

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "lib", "repo.generated.ts");
const REPO = process.env.AGENTTY_REPO || "1ay1/agentty";
const API = `https://api.github.com/repos/${REPO}`;

function bail(msg) {
  console.warn(`[fetch-repo] ${msg} — keeping committed repo data.`);
  process.exit(0); // never break the deploy
}

const headers = {
  "User-Agent": "agentty-site-build",
  Accept: "application/vnd.github+json",
};
if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;

async function fetchJson(url) {
  const ctrl = new AbortController();
  const to = setTimeout(() => ctrl.abort(), 10000);
  try {
    const res = await fetch(url, { headers, signal: ctrl.signal });
    if (!res.ok) return { error: `GitHub API returned ${res.status}` };
    return { data: await res.json() };
  } catch (e) {
    return { error: `fetch failed: ${e?.message ?? e}` };
  } finally {
    clearTimeout(to);
  }
}

const { data: repo, error } = await fetchJson(API);
if (error) bail(error);
if (!repo || typeof repo.stargazers_count !== "number") {
  bail("response missing stargazers_count");
}

const data = {
  stars: repo.stargazers_count ?? 0,
  forks: repo.forks_count ?? 0,
  openIssues: repo.open_issues_count ?? 0,
  watchers: repo.subscribers_count ?? repo.watchers_count ?? 0,
  description: repo.description || "",
  htmlUrl: repo.html_url || `https://github.com/${REPO}`,
  pushedAt: repo.pushed_at || "",
  fetchedAt: new Date().toISOString(),
};

const banner = `// AUTO-GENERATED by scripts/fetch-repo.mjs — DO NOT EDIT BY HAND.
// Pulled from the GitHub repo API on each deploy so the site's star / fork
// counts never drift from the real repo. Last fetched: ${data.fetchedAt}.
`;
const body = `export const repoStats = ${JSON.stringify(data, null, 2)} as const;

export type RepoStats = typeof repoStats;
`;

writeFileSync(OUT, banner + "\n" + body);

console.log(
  `[fetch-repo] ${REPO}\n` +
    `  stars      : ${data.stars}\n` +
    `  forks      : ${data.forks}\n` +
    `  openIssues : ${data.openIssues}\n` +
    `  watchers   : ${data.watchers}\n` +
    `  → wrote ${OUT}`,
);
