#!/usr/bin/env node
// Measure the REAL agentty binary and emit lib/stats.generated.ts so the site
// can never drift from the shipped binary. Run automatically by deploy.sh
// (and safe to run by hand: `node scripts/measure-stats.mjs`).
//
// What it captures:
//   • exact binary size on disk (bytes → MB, 1 decimal)
//   • whether it is statically linked
//   • version string from `--version`
//   • median cold-start for `--version` and `--help` (ms)
//
// If the binary can't be found or run, it leaves any existing generated file
// untouched and exits 0 — a deploy must never fail just because the local box
// doesn't have the binary installed.

import { execFileSync, spawnSync } from "node:child_process";
import { statSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "lib", "stats.generated.ts");

// ── locate the binary ────────────────────────────────────────────────────
function findBinary() {
  // explicit override wins
  if (process.env.AGENTTY_BIN && existsSync(process.env.AGENTTY_BIN)) {
    return process.env.AGENTTY_BIN;
  }
  // PATH lookup (avoid shell:true; scan PATH entries directly)
  for (const dir of (process.env.PATH || "").split(":")) {
    if (!dir) continue;
    const p = join(dir, "agentty");
    if (existsSync(p)) return p;
  }
  // common install locations
  for (const p of [
    join(homedir(), ".local", "bin", "agentty"),
    join(homedir(), "bin", "agentty"),
    "/usr/local/bin/agentty",
    "/usr/bin/agentty",
  ]) {
    if (existsSync(p)) return p;
  }
  return null;
}

// ── helpers ──────────────────────────────────────────────────────────────
function median(nums) {
  const s = [...nums].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}

// median wall-clock (ms) to run `bin args`, over N runs after a warmup
function timeRun(bin, args, runs = 15) {
  // warm the page cache / fs first so we measure steady-state cold start
  for (let i = 0; i < 3; i++) {
    try { execFileSync(bin, args, { stdio: "ignore" }); } catch {}
  }
  const samples = [];
  for (let i = 0; i < runs; i++) {
    const t0 = process.hrtime.bigint();
    try {
      execFileSync(bin, args, { stdio: "ignore" });
    } catch {
      // --help / --version may exit non-zero on some builds; timing still valid
    }
    const t1 = process.hrtime.bigint();
    samples.push(Number(t1 - t0) / 1e6); // ns → ms
  }
  return median(samples);
}

function isStatic(bin) {
  const r = spawnSync("file", [bin], { encoding: "utf8" });
  if (r.status === 0 && /statically linked|not a dynamic executable/i.test(r.stdout)) return true;
  const ldd = spawnSync("ldd", [bin], { encoding: "utf8" });
  if (ldd.status !== 0 || /not a dynamic executable/i.test(ldd.stdout + ldd.stderr)) return true;
  return false;
}

// round a small ms value to a friendly label: 2.4 → "~2 ms", 0.8 → "<1 ms"
function msLabel(ms) {
  if (ms < 1) return "<1 ms";
  return `~${Math.round(ms)} ms`;
}

// ── run ──────────────────────────────────────────────────────────────────
const bin = findBinary();
if (!bin) {
  console.warn("[measure-stats] agentty binary not found — keeping existing generated stats.");
  process.exit(0);
}

let sizeBytes = 0;
try {
  sizeBytes = statSync(bin).size;
} catch {
  console.warn("[measure-stats] could not stat binary — keeping existing stats.");
  process.exit(0);
}
const sizeMB = (sizeBytes / 1048576).toFixed(1);

let version = "";
try {
  version = execFileSync(bin, ["--version"], { encoding: "utf8" }).trim().split(/\s+/).pop() || "";
} catch {}

const verMs = timeRun(bin, ["--version"]);
const helpMs = timeRun(bin, ["--help"]);
const coldMs = Math.min(verMs, helpMs); // headline = the faster of the two
const staticLinked = isStatic(bin);

const stats = {
  binarySizeBytes: sizeBytes,
  binarySizeMB: `${sizeMB} MB`,
  version,
  staticLinked,
  coldStartMs: Number(coldMs.toFixed(2)),
  coldStartLabel: msLabel(coldMs),
  versionMs: Number(verMs.toFixed(2)),
  helpMs: Number(helpMs.toFixed(2)),
  measuredAt: new Date().toISOString(),
  source: bin,
};

const banner = `// AUTO-GENERATED by scripts/measure-stats.mjs — DO NOT EDIT BY HAND.
// Regenerated on every deploy from the real agentty binary, so the site can
// never drift from what actually ships. Last measured: ${stats.measuredAt}.
`;

const body = `export const measuredStats = ${JSON.stringify(stats, null, 2)} as const;

export type MeasuredStats = typeof measuredStats;
`;

writeFileSync(OUT, banner + "\n" + body);

console.log(
  `[measure-stats] ${bin}\n` +
    `  size      : ${stats.binarySizeMB} (${sizeBytes} bytes)\n` +
    `  static    : ${staticLinked}\n` +
    `  version   : ${version || "(unknown)"}\n` +
    `  --version : ${stats.versionMs} ms\n` +
    `  --help    : ${stats.helpMs} ms\n` +
    `  headline  : ${stats.coldStartLabel}\n` +
    `  → wrote ${OUT}`,
);
